### ISSUE TITLE
Sign Up (Mobile/Desktop)

### ISSUE THREAD

**Issue by zblock** [not-the-droids/Finesse#3]
Sign Up D - https://xd.adobe.com/view/06e309e3-53d4-49b2-b716-c566752f3063-53b0/screen/36bafc14-eb5b-4e11-a71b-eb95ee69f407
----------
Sign Up M - https://xd.adobe.com/view/cc4d499b-422b-423b-9ee7-da3d0482d991-991e/screen/3a333001-2b6e-4b5b-af34-4246481987e5

**Comment by ohlin** [comment]
Did this get merged and deployed? Looks completely different from mockups: https://finesse-stealth-page-git-redesign.finesse-tech-fam.vercel.app/sign-up

![image](https://user-images.githubusercontent.com/265998/99109781-2e7df800-259e-11eb-9f9d-7a16a0f5fb7f.png)

vs.

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/265998/99109803-39d12380-259e-11eb-96a7-8fd3564f2768.png">

**Comment by mattryavec** [comment]
Fix deployed

**Comment by ohlin** [comment]
@mattryavec not sure the fix got deployed after all
